<a href="https://colab.research.google.com/github/kingajutrzenka/Data-Science/blob/main/algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Algebra liniowa [*]

In [2]:
import numpy as np
np.__version__

'2.0.2'

wektory

In [3]:
v1 = np.array([-1, 4])
print(v1)
# to jest wektor o początku 0 i końcówce 4
# liczymy długość:
np.linalg.norm(v1)

[-1  4]


np.float64(4.123105625617661)

długość wektora w przestrzeni  R^n (norma euklidesowa)

In [4]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)
# jest to w przetsrzeni R^3

np.float64(19.209372712298546)

odleglość punktów w przestrzeni R^n

In [5]:
# na płaszczyźnie
p = np.array([3, 0])
q = np.array([0, 4])
o = np.linalg.norm(p - q)
print(o)
# w przestrzeni R^3
z = np.array([3, 0, 1])
y = np.array([0, 4, 2])
h = np.linalg.norm(z - y)
print(h)


5.0
5.0990195135927845


w przypadku mnożenia macierzy liczba kolumn w lewej macierzy musi się zgadzać z liczbą wierszy w  prawej

In [6]:
x = np.array([[5, 3], [3, 9]])
y = np.array([[1], [-1]])
print(np.dot(x, y))
print(x)
print(y)
# print(np.dot(y, x)) wtedy wyskoczy błąd

[[ 2]
 [-6]]
[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [7]:
x = np.array([[2, -1, 3],
              [3, 1, 0]])
y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(np.dot(x, y))

[[13  9 -4]
 [ 6  2 -1]]


In [8]:
o = np.array([[2, 3, 4],
             [5, 6, 7],
             [8, 9, 10]])
print(o)
wyznacznik_macierzy = np.linalg.det(o)
print(wyznacznik_macierzy)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
0.0


In [9]:
macierz = np.array([[12, 33],
                    [15, 8]])
wm = np.linalg.det(macierz)
print(wm)

-399.0000000000001


**ślad macierzy** - suma elementów na przekątnej (głownej tzn lewa góra - prawa dół)

In [10]:
macierz = np.array([[12, 33],
                    [15, 8]])
print(np.trace(macierz))

20


macierz jednostkowa [1, 0, 0], generowanie:

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [13]:
np.eye(5, dtype= "int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

macierz odwrotna, gdy A*B = B#A = 1

In [14]:
A = np.array([[2, 4], [-1, 3]])
print(A)
B = np.linalg.inv(A)
print(B)
s = np.dot(A, B)
# bez notacji mat. możemy mieć większą precyzję:
print(np.set_printoptions(precision=4, suppress=True))
print(s)
print(np.dot(B, A))
# powstają macierze jednostkowe :)

[[ 2  4]
 [-1  3]]
[[ 0.3 -0.4]
 [ 0.1  0.2]]
None
[[1. 0.]
 [0. 1.]]
[[ 1. -0.]
 [ 0.  1.]]


**macierz transponowana** - zamiana wierszy na kolumne i kolumn na wiersze

In [15]:
Z = np.array([[2,4], [3,5], [2,7]])
print(Z)
u = (np.transpose(Z))
print(u)
b = Z.T
print(b)
# np.transpose() = x.T

[[2 4]
 [3 5]
 [2 7]]
[[2 3 2]
 [4 5 7]]
[[2 3 2]
 [4 5 7]]


**rozwiązywanie układów równań**

In [16]:
# Rozwiązywanie układu równań liniowych
# Przykład:
# 2x + 3y = 6
# x  + y  = 2

# Reprezentacja macierzowa:
# [[2, 3], [1, 1]] * [x, y] = [6, 2]

A = np.array([[2, 3], [1, 1]])
b = np.array([6, 2])

# Rozwiązanie układu równań
x = np.linalg.solve(A, b)

print("Rozwiązanie układu równań (x, y):")
print(x)

Rozwiązanie układu równań (x, y):
[0. 2.]


In [17]:
# 2x + 4y = 10
# x - y = -1
A = np.array([[2, 4], [1, -1]]) # przepisujemy współczynniki przed stałymi
B= np.array([10, -1]) # przepisujemy stałe
X = np.linalg.solve(A, B)
print(X)

[1. 2.]
