<a href="https://colab.research.google.com/github/kingajutrzenka/Data-Science/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

uczymy się numpy

# Nowa sekcja

In [53]:
pip install numpy

In [54]:
import numpy as np
np.__version__

'2.0.2'

In [55]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [56]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``o

In [57]:
# 1D Array
x = np.array([1, 3])
y = np.array([2, 5, 7, 14])
print(x)
print(y)
# powstaje macierz 1 x ...

[1 3]
[ 2  5  7 14]


In [58]:
# 2D Array
z = np.array([[1, 2], [-3, 1]])
w = np.array([[1, 2, 4, 4], [5, 8, 9, 0]])
print(z)
print(w)
# to jest macierz 2 x ...

[[ 1  2]
 [-3  1]]
[[1 2 4 4]
 [5 8 9 0]]


In [59]:
# 3D Array
m = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]]]
)
print(m)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


typy danych:

In [60]:
A = np.array([1, 2, 3])
print(A.dtype)
B = np.array([1.0, 2.3, 3.3])
print(B.dtype)
C = np.array([1, 2, 3], dtype=float)
print(C.dtype)
D = np.array([1, 2, 3], dtype=complex)
print(D.dtype)
print(D)
# Liczby zespolone :///
E = np.array([True, False])
print(E.dtype)
print(E)

int64
float64
float64
complex128
[1.+0.j 2.+0.j 3.+0.j]
bool
[ True False]


In [61]:
e = np.zeros(shape=(4, 10))
print(e)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


generuje macierz 4 x 10 z samych zer

In [62]:
q = np.zeros(shape=(4, 10), dtype='int')
print(q)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


generuje macierz z samych 0 bez tych kropek XDD

In [63]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

macierz jedynek

In [64]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

bez kropek

In [65]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

dzięki temu mamy same 4 ⛅

In [66]:
s = np.arange(10)
print(s)

[0 1 2 3 4 5 6 7 8 9]


generuj liczby od 0 do 9

In [67]:
y = np.arange(1, 10)
print(y)

[1 2 3 4 5 6 7 8 9]


In [68]:
h = np.arange(1, 10, 2)
print(h)

[1 3 5 7 9]


In [69]:
j = np.arange(100, 10, -10)
print(j)

[100  90  80  70  60  50  40  30  20]


In [70]:
t = np.arange(0, 1, 0.05)
print(t)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [71]:
o = np.linspace(start=0, stop=1, num=11)
print(o)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


num = na ile równych części dzielimy równo przedział

In [72]:
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [73]:
p = A.reshape((3, 5))
print(p)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


funkcja reshape tworzy macierz, gdy x.reshape((..., -1)) to python sam dobierze ilość kolumn do podanej liczby wierszy

i może być też na odwrót

In [74]:
A = np.array([3, 1, 4, 3])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 3]
[ 3 -1  3  2]


In [75]:
A + B

array([6, 0, 7, 5])

In [76]:
A - B

array([0, 2, 1, 1])

In [77]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.5       ])

In [78]:
A * B

array([ 9, -1, 12,  6])

In [79]:
A + 3

array([6, 4, 7, 6])

In [80]:
A + 3 * B

array([12, -2, 13,  9])

Mamy jeszcze funkcje add, subtract, multiply, divide, ale po chuj ich używać

In [81]:
x = np.array([[1, 3], [-2, 0]])
y = np.array([[6, 0], [-1, 2]])
print(x)
print(y)
print(x * y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]
[[6 0]
 [2 0]]


jakaś chujowa metoda macierzy by numpy

generowanie liczb pseudolosowych

In [82]:
np.random.seed(0)

przez to dostajemy zawsze ten sam wynik

In [83]:
np.random.randn()

1.764052345967664

In [84]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

10 liczb z rozkładu normalnego

In [85]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

może służyć jako histogram rozkładu normalnego

In [86]:
np.random.rand()

0.1965823616800535

losowa liczba/liczby z przedziału [0,1)

In [87]:
np.random.randint(10)

0

losowa liczba całkowita z przedizalu 0- 10

In [88]:
np.random.randint(low=10, high=101, size=10)

array([79, 10, 60, 46, 44, 58, 13, 52, 87, 31])

muszą być tu koniecznie te napisy low high size

In [89]:
r = np.random.choice([4, 2, 1, 3, 5])
print(r)

2


zwraca losowy element z listy

In [90]:
t = np.random.choice(['python', 'java', 'sql'])
print(t)

python


In [91]:
data = np.arange(10)
print(data)

[0 1 2 3 4 5 6 7 8 9]


In [92]:
np.random.shuffle(data)
print(data)

[0 5 8 4 6 1 9 3 7 2]


miesza sobie kolejność liczb

In [93]:
print(data)

[0 5 8 4 6 1 9 3 7 2]


In [94]:
liczba_eulera = np.exp(1)
print(liczba_eulera)

2.718281828459045


In [95]:
liczba_eulera_do_kwadratu = np.exp(2)
print(liczba_eulera_do_kwadratu)

7.38905609893065


In [96]:
pierwiastek = int(np.sqrt(9))
print(pierwiastek)

3


In [97]:
wartość_logiczna = str(np.all([2, 3, 1]))
print(wartość_logiczna)

True


In [98]:
np.any([1, 0, 2])

np.True_

In [99]:
A = np.random.rand(5)
print(A)

[0.21682214 0.56518887 0.86510256 0.50896896 0.91672295]


In [100]:
wartość_maksymalna_index = np.argmax(A)
wartość_maksymalna = np.max(A) # Define the variable
print(f"Maximum value: {wartość_maksymalna}")
print(f"Index of maximum value: {wartość_maksymalna_index}")

Maximum value: 0.9167229540194608
Index of maximum value: 4


index wartości max

In [101]:
max = np.max(A)
print(max)

0.9167229540194608


i tak samo można z min

In [102]:
np.argsort(A)

array([0, 3, 1, 2, 4])

od najmniejszego indexu do największego

In [103]:
średnia = np.mean(A)
print(średnia)

0.6145610960448558


In [104]:
mediana = np.median(A)
print(mediana)

0.5651888666048753


In [105]:
odchylenie_standardowe = np.std(A)
print(odchylenie_standardowe)

0.2552866660701157


In [106]:
od5 = np.std(3)
print(od5)

0.0


In [107]:
C = np.arange(20)
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


wycinanie: C[idx], A[start:stop], A[start: ] i pokoazuje nam WYCIĘTA część!

In [110]:
C[3]

np.int64(3)

In [111]:
C[3: ]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [112]:
C[3: 8]

array([3, 4, 5, 6, 7])

In [113]:
C[:3]

array([0, 1, 2])

In [ ]:
C[1, 2]

In [114]:
C = C.reshape(4, 5)
print(C)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


wycinanie kolumn i elementów

In [115]:
C[:, 0]

array([ 0,  5, 10, 15])

In [116]:
C[0, 0]

np.int64(0)

In [119]:
C[0:4, 0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [123]:
C[3, :]

array([15, 16, 17, 18, 19])

Literacja po tablicach

In [124]:
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [126]:
for row in C:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [127]:
for row in C:
    print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [129]:
for row in C:
  print(row[0])

0
5
10
15


In [130]:
for item in C.flat:
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [131]:
C.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [132]:
C.shape

(4, 5)

In [134]:
C.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [135]:
C.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Ravel wypisuje T transponuje

In [140]:
B = np.arange(-10, 10, 0.5)
B = B.reshape(10, -1)
print(B)

[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]


In [141]:
B > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

to jest maska logiczna ⏫

In [145]:
np.bitwise_and(B > -5, B < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [146]:
B[B > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])