<a href="https://colab.research.google.com/github/kingajutrzenka/Data-Science/blob/main/podstawyNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

uczymy się numpy

In [4]:
pip install numpy

In [5]:
import numpy as np
np.__version__

'2.0.2'

In [7]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [8]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``o

In [10]:
# 1D Array
x = np.array([1, 3])
y = np.array([2, 5, 7, 14])
print(x)
print(y)
# powstaje macierz 1 x ...

[1 3]
[ 2  5  7 14]


In [13]:
# 2D Array
z = np.array([[1, 2], [-3, 1]])
w = np.array([[1, 2, 4, 4], [5, 8, 9, 0]])
print(z)
print(w)
# to jest macierz 2 x ...

[[ 1  2]
 [-3  1]]
[[1 2 4 4]
 [5 8 9 0]]


In [16]:
# 3D Array
m = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]]]
)
print(m)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


dtype('int64')

typy danych:

In [21]:
A = np.array([1, 2, 3])
print(A.dtype)
B = np.array([1.0, 2.3, 3.3])
print(B.dtype)
C = np.array([1, 2, 3], dtype=float)
print(C.dtype)
D = np.array([1, 2, 3], dtype=complex)
print(D.dtype)
print(D)
# Liczby zespolone :///
E = np.array([True, False])
print(E.dtype)
print(E)

int64
float64
float64
complex128
[1.+0.j 2.+0.j 3.+0.j]
bool
[ True False]
