<a href="https://colab.research.google.com/github/kingajutrzenka/Data-Science/blob/main/statystyka_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**funkcje statystyczne numpy**

In [29]:
import numpy as np
np.__version__

'2.0.2'

In [30]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [31]:
#suma wszystkich elementów:
a =price.sum()
print(a)
#sumowanie po kolumnach 0
b = price.sum(axis=0)
print(b)
#sumowanie po wierszach 1
c = price.sum(axis=1)
print(c)

4650.1
[  37.1   39.2   35.8   38.  4500. ]
[1049.7 2049.4 1551. ]


In [32]:
#minimum:
print(price.min())
print(price.min(axis=0))
print(price.min(axis=1))

11.7
[  12.2   12.8   11.7   12.2 1000. ]
[11.9 11.7 12.2]


In [33]:
#cena max
print(price.max())
print(price.max(axis=0))
print(price.max(axis=1))

2000.0
[  12.5   13.4   12.2   13.2 2000. ]
[1000. 2000. 1500.]


In [34]:
#mediana
print(np.median(price))

12.6


In [35]:
np.set_printoptions(precision=4, suppress=True)

In [36]:
#wariancja
np.var(price)

np.float64(387354.5619555555)

In [37]:
#średnia
np.mean(price, axis=0, dtype = "int")

array([  12,   12,   11,   12, 1500])

In [38]:
#odchylenie standardowe
np.std(price)

np.float64(622.3781502877133)

**wzory**
* ogólnie: np.coś(nazwa)
* może być też np.coś(nazwa, axis=0/1)
* można też dodać tak jak axis dtype